---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ['true', 'false']
  comments:
    min-spaces-from-content: 1

ignore: |
  node_modules/
  .git/
  dist/
  build/
